// Mock data to use when backend is not available
// This ensures frontend works independently during development

export const MOCK_PROVIDERS = [
  {
    id: '1',
    name: 'XL Home',
    slug: 'xlhome',
    description: 'Layanan internet fiber optik tercepat dengan kualitas terbaik',
    tagline: 'Koneksi Berkecepatan Tinggi',
    logo: '',
    type: 'fiber' as const,
    rating: 4.4,
    reviewCount: 18420,
    minPrice: 199000,
    maxSpeed: 1000,
    features: ['Very fast', 'Free WiFi Router', 'Unlimited'],
    pros: ['Sangat cepat', 'Customer service bagus', 'Area coverage luas'],
    cons: ['Harga agak mahal', 'Instalasi lambat saat peak hours'],
    website: 'https://xl.co.id',
    phone: '087 777 777 777',
    isActive: true,
    isFeatured: true,
    coverageAreas: [
      { id: '1', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
      { id: '2', province: 'Jawa Barat', city: 'Bandung', district: 'Bandung', postalCode: '40123', isAvailable: true },
      { id: '3', province: 'Jawa Timur', city: 'Surabaya', district: 'Surabaya', postalCode: '60123', isAvailable: true },
    ],
    createdAt: '2024-01-01',
    updatedAt: '2024-03-08',
  },
  {
    id: '2',
    name: 'XL Gamer',
    slug: 'xl-gamer',
    description: 'Internet khusus gaming dengan latency ultra rendah',
    tagline: 'Pengalaman Gaming Tanpa Lag',
    logo: '',
    type: 'fiber' as const,
    rating: 4.6,
    reviewCount: 8200,
    minPrice: 299000,
    maxSpeed: 500,
    features: ['Gaming priority', 'Ultra-low latency', 'Dedicated BW'],
    pros: ['Ping rendah untuk gaming', 'Stabil', 'Support 24/7'],
    cons: ['Lebih mahal dari paket biasa', 'Area coverage terbatas'],
    website: 'https://xl.co.id/gamer',
    phone: '087 777 777 777',
    isActive: true,
    isFeatured: true,
    coverageAreas: [
      { id: '4', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
      { id: '5', province: 'Jawa Barat', city: 'Bandung', district: 'Bandung', postalCode: '40123', isAvailable: true },
    ],
    createdAt: '2024-02-01',
    updatedAt: '2024-03-08',
  },
] as const;

export const MOCK_PACKAGES = [
  {
    id: '1',
    name: 'XL Home 50Mbps',
    slug: 'xl-home-50',
    providerId: '1',
    provider: {
      id: '1',
      name: 'XL Home',
      slug: 'xlhome',
      description: 'Layanan internet fiber optik tercepat dengan kualitas terbaik',
      tagline: 'Koneksi Berkecepatan Tinggi',
      logo: '',
      type: 'fiber' as const,
      rating: 4.4,
      reviewCount: 18420,
      minPrice: 199000,
      maxSpeed: 1000,
      features: ['Very fast', 'Free WiFi Router', 'Unlimited'],
      pros: ['Sangat cepat', 'Customer service bagus', 'Area coverage luas'],
      cons: ['Harga agak mahal', 'Instalasi lambat saat peak hours'],
      website: 'https://xl.co.id',
      phone: '087 777 777 777',
      isActive: true,
      isFeatured: true,
      coverageAreas: [
        { id: '1', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
      ],
      createdAt: '2024-01-01',
      updatedAt: '2024-03-08',
    },
    speed: 50,
    price: 199000,
    installationFee: 0,
    contractMonths: 12,
    quota: 'unlimited' as const,
    latency: 15,
    features: ['Unlimited', 'Free WiFi Router', 'TV Lokal'],
    isPopular: false,
    isFeatured: false,
    category: 'basic' as const,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-03-08',
  },
  {
    id: '2',
    name: 'XL Home 150Mbps',
    slug: 'xl-home-150',
    providerId: '1',
    provider: {
      id: '1',
      name: 'XL Home',
      slug: 'xlhome',
      description: 'Layanan internet fiber optik tercepat dengan kualitas terbaik',
      tagline: 'Koneksi Berkecepatan Tinggi',
      logo: '',
      type: 'fiber' as const,
      rating: 4.4,
      reviewCount: 18420,
      minPrice: 199000,
      maxSpeed: 1000,
      features: ['Very fast', 'Free WiFi Router', 'Unlimited'],
      pros: ['Sangat cepat', 'Customer service bagus', 'Area coverage luas'],
      cons: ['Harga agak mahal', 'Instalasi lambat saat peak hours'],
      website: 'https://xl.co.id',
      phone: '087 777 777 777',
      isActive: true,
      isFeatured: true,
      coverageAreas: [
        { id: '1', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
      ],
      createdAt: '2024-01-01',
      updatedAt: '2024-03-08',
    },
    speed: 150,
    price: 299000,
    installationFee: 0,
    contractMonths: 12,
    quota: 'unlimited' as const,
    latency: 10,
    features: ['Unlimited tanpa FUP', 'Free Installation', 'Router WiFi 6'],
    isPopular: true,
    isFeatured: true,
    category: 'standard' as const,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-03-08',
  },
  {
    id: '3',
    name: 'XL Gamer 300Mbps',
    slug: 'xl-gamer-300',
    providerId: '2',
    provider: {
      id: '2',
      name: 'XL Gamer',
      slug: 'xl-gamer',
      description: 'Internet khusus gaming dengan latency ultra rendah',
      tagline: 'Pengalaman Gaming Tanpa Lag',
      logo: '',
      type: 'fiber' as const,
      rating: 4.6,
      reviewCount: 8200,
      minPrice: 299000,
      maxSpeed: 500,
      features: ['Gaming priority', 'Ultra-low latency', 'Dedicated BW'],
      pros: ['Ping rendah untuk gaming', 'Stabil', 'Support 24/7'],
      cons: ['Lebih mahal dari paket biasa', 'Area coverage terbatas'],
      website: 'https://xl.co.id/gamer',
      phone: '087 777 777 777',
      isActive: true,
      isFeatured: true,
      coverageAreas: [
        { id: '4', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
      ],
      createdAt: '2024-02-01',
      updatedAt: '2024-03-08',
    },
    speed: 300,
    price: 399000,
    installationFee: 0,
    contractMonths: 0,
    quota: 'unlimited' as const,
    latency: 3,
    features: ['Gaming Priority Traffic', 'Ultra-low Latency', 'Dedicated BW'],
    isPopular: false,
    isFeatured: true,
    category: 'gaming' as const,
    isActive: true,
    createdAt: '2024-02-01',
    updatedAt: '2024-03-08',
  },
] as const;

export const MOCK_BLOG_POSTS = [
  {
    id: '1',
    title: 'Cara Memilih Paket Internet Terbaik Untuk Rumah Anda',
    slug: 'cara-memilih-paket-internet',
    content: 'Panduan lengkap memilih paket internet yang sesuai dengan kebutuhan dan budget Anda. Internet adalah kebutuhan essential untuk kehidupan modern.',
    excerpt: 'Pelajari tips dan trik memilih paket internet yang sesuai dengan kebutuhan rumah Anda.',
    featuredImage: '',
    category: {
      id: 'cat-1',
      name: 'Tutorial',
      slug: 'tutorial',
      description: 'Tutorial dan panduan lengkap',
      color: '#3B82F6',
    },
    categoryId: 'cat-1',
    author: {
      id: '1',
      name: 'Daffa Tabiano',
      avatar: '',
      bio: 'Tech writer dan internet enthusiast',
    },
    authorId: '1',
    tags: ['internet', 'tips', 'tutorial'],
    readTime: 5,
    viewCount: 2540,
    isPublished: true,
    publishedAt: '2025-03-15T10:00:00Z',
    seoTitle: 'Cara Memilih Paket Internet Terbaik',
    seoDescription: 'Panduan lengkap memilih paket internet yang sesuai dengan kebutuhan rumah Anda',
    seoKeywords: ['internet', 'paket', 'tips memilih'],
    createdAt: '2025-03-15',
    updatedAt: '2025-03-15',
  },
] as const;

export const MOCK_REVIEWS = [
  {
    id: '1',
    userName: 'Budi Santoso',
    userAvatar: '',
    userCity: 'Jakarta',
    provider: {
      id: '1',
      name: 'XL Home',
      slug: 'xlhome',
      description: 'Layanan internet fiber optik tercepat dengan kualitas terbaik',
      tagline: 'Koneksi Berkecepatan Tinggi',
      logo: '',
      type: 'fiber' as const,
      rating: 4.4,
      reviewCount: 18420,
      minPrice: 199000,
      maxSpeed: 1000,
      features: ['Very fast', 'Free WiFi Router', 'Unlimited'],
      pros: ['Sangat cepat', 'Customer service bagus', 'Area coverage luas'],
      cons: ['Harga agak mahal', 'Instalasi lambat saat peak hours'],
      website: 'https://xl.co.id',
      phone: '087 777 777 777',
      isActive: true,
      isFeatured: true,
      coverageAreas: [
        { id: '1', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
      ],
      createdAt: '2024-01-01',
      updatedAt: '2024-03-08',
    },
    providerId: '1',
    rating: 5,
    speedRating: 5,
    priceRating: 4,
    supportRating: 5,
    comment: 'Saya sudah menggunakan XL Home selama 2 tahun dan sangat puas dengan layanannya. Internet stabil dan customer service responsif.',
    isVerified: true,
    isApproved: true,
    helpfulCount: 45,
    createdAt: '2025-03-01',
  },
] as const;

export const MOCK_DASHBOARD_STATS = {
  totalProviders: 2,
  totalPackages: 3,
  totalReviews: 100,
  totalBlogPosts: 1,
  totalPageViews: 25400,
  newReviewsThisMonth: 12,
  pendingReviews: 5,
  topProviders: [
    {
      provider: {
        id: '1',
        name: 'XL Home',
        slug: 'xlhome',
        description: 'Layanan internet fiber optik tercepat dengan kualitas terbaik',
        tagline: 'Koneksi Berkecepatan Tinggi',
        logo: '',
        type: 'fiber' as const,
        rating: 4.4,
        reviewCount: 18420,
        minPrice: 199000,
        maxSpeed: 1000,
        features: ['Very fast', 'Free WiFi Router', 'Unlimited'],
        pros: ['Sangat cepat', 'Customer service bagus', 'Area coverage luas'],
        cons: ['Harga agak mahal', 'Instalasi lambat saat peak hours'],
        website: 'https://xl.co.id',
        phone: '087 777 777 777',
        isActive: true,
        isFeatured: true,
        coverageAreas: [
          { id: '1', province: 'DKI Jakarta', city: 'Jakarta', district: 'Jakarta Selatan', postalCode: '12950', isAvailable: true },
        ],
        createdAt: '2024-01-01',
        updatedAt: '2024-03-08',
      },
      score: 95,
    },
  ],
} as const;
